insert into country values(1,'India');
insert into country values(2,'USA');
insert into state values(1,1,'Andhra Pradesh');
insert into state values(2,1,'Karnataka');
insert into state values(3,2,'New Jersy');
insert into state values(4,2,'Ohio');
insert into city values(1,'Vizag',1);
insert into city values(2,'Guntur',1);
insert into city values(3,'Banglore',2);
insert into city values(4,'Mysore',2);
insert into city values(6,'Maywood',3);
insert into city values(7,'Westwood',3);
insert into city values(8,'Oakwood',4);
insert into city values(9,'Cuyahoga County',4);